"""
INVENT — Databricks Genie Agent.

A first-class consumption channel over the same governed Metric Views that
INVENT publishes to Unity Catalog.

The page supports:
  * domain-aware Genie Agent selection from the metadata registry
  * direct opening of the Databricks Genie UI
  * optional embedded Agent Mode API chat from inside INVENT
  * follow-up questions using the same Genie conversation
"""

from __future__ import annotations

import json

import requests
import streamlit as st

from theme import (
    navigate_to,
    inject_base_css,
    render_sidebar_brand,
    page_header,
    section_title,
)
from registry import list_domains
import security_fabric as security


inject_base_css()
render_sidebar_brand()

page_header(
    "Genie AI",
    "Databricks-native conversational analytics over INVENT's governed semantic model",
)

domains = list_domains()

if not domains:
    st.info(
        "No published domains are available yet. "
        "Publish a domain first."
    )
    if st.button(
        "Go to Business Model →",
        type="primary",
    ):
        navigate_to("Business Model")
    st.stop()

domain_names = [
    d.domain_name
    for d in domains
]

selected_domain = st.selectbox(
    "Published domain",
    domain_names,
    key="genie_domain_selector",
)

entry = next(
    d
    for d in domains
    if d.domain_name == selected_domain
)

space_id = (
    entry.genie_space_id
    or security.genie_space_id_from_secrets(
        entry.domain_name
    )
)

st.markdown(
    f"""
    **Domain:** `{entry.domain_name}`

    **Metric View:** `{entry.metric_view}`

    **Fact Tables:** {len(getattr(entry, "fact_tables", []) or [entry.fact_table])}

    **Measures:** {", ".join(entry.measures) or "None"}

    **Dimensions:** {", ".join(entry.dimensions) or "None"}
    """
)

if not space_id:
    st.warning(
        "This domain does not yet have a Genie Agent. "
        "Republish the domain with Genie auto-creation enabled, "
        "or map an existing Agent in Streamlit Secrets."
    )
    st.stop()

if not security._is_valid_genie_agent_id(space_id):
    st.error(
        "This domain has a stale or invalid Genie Agent ID. "
        "Republish the domain with automatic Genie recovery enabled."
    )
    st.caption(f"Configured value: `{space_id}`")
    st.stop()

genie_url = security.genie_ui_url(
    space_id
)

st.markdown(
    "### 🧞 Databricks Genie AI"
)

st.caption(
    "Genie uses the domain's published Metric View and its governed "
    "metadata to translate natural-language questions into Databricks "
    "analytics."
)

st.link_button(
    "Open Genie Agent in Databricks →",
    genie_url,
    use_container_width=True,
)

st.divider()

# ---------------------------------------------------------------------
# Agent Mode API chat
# ---------------------------------------------------------------------

section_title(
    "Ask Genie from INVENT",
    "The response is generated by the domain's Databricks Genie Agent.",
)

if "genie_conversation_id" not in st.session_state:
    st.session_state.genie_conversation_id = None

if (
    st.session_state.get("genie_active_domain")
    != entry.domain_name
):
    st.session_state.genie_conversation_id = None
    st.session_state.genie_active_domain = (
        entry.domain_name
    )

question = st.text_input(
    "Ask a business question",
    placeholder=(
        "e.g. What are the key KPIs for this domain?"
    ),
    key="genie_question",
)

enable_viz = st.checkbox(
    "Allow Genie to generate visualizations",
    value=True,
    key="genie_enable_viz",
)

ask = st.button(
    "Ask Genie →",
    type="primary",
    disabled=not question.strip(),
)

if ask:

    host = str(st.secrets.get("DATABRICKS_HOST", "")).rstrip("/")
    token = str(st.secrets.get("DATABRICKS_TOKEN", ""))
    if not host or not token:
        st.error("Databricks authentication is not configured for Genie chat.")
        st.stop()

    url = (
        f"{host}/api/2.0/genie/agents/"
        f"{space_id}/responses"
    )

    payload = {
        "input": [
            {
                "type": "message",
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": question.strip(),
                    }
                ],
            }
        ],
        "enable_viz": bool(enable_viz),
    }

    if st.session_state.genie_conversation_id:
        payload["conversation_id"] = (
            st.session_state.genie_conversation_id
        )

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Accept": "text/event-stream",
    }

    final_response = None
    latest_status = "running"

    try:

        with st.status(
            "Genie is analyzing the governed semantic model…",
            expanded=False,
        ) as status:

            response = requests.post(
                url,
                headers=headers,
                json=payload,
                timeout=300,
                stream=True,
            )

            response.raise_for_status()

            event_name = None

            for raw_line in response.iter_lines(
                decode_unicode=True
            ):

                if not raw_line:
                    continue

                line = raw_line.strip()

                if line.startswith("event:"):
                    event_name = line[
                        len("event:"):
                    ].strip()
                    continue

                if not line.startswith(
                    "data:"
                ):
                    continue

                raw_data = line[
                    len("data:"):
                ].strip()

                try:
                    event = json.loads(
                        raw_data
                    )
                except json.JSONDecodeError:
                    continue

                event_type = (
                    event.get("type")
                    or event_name
                )

                if event_type == "response.created":

                    response_obj = event.get(
                        "response",
                        {},
                    )

                    st.session_state.genie_conversation_id = (
                        response_obj.get(
                            "conversation_id"
                        )
                        or st.session_state.genie_conversation_id
                    )

                elif event_type == "response.completed":

                    final_response = event.get(
                        "response"
                    )

                    latest_status = (
                        final_response or {}
                    ).get(
                        "status",
                        "completed",
                    )

                elif event_type == "response.failed":

                    failed = event.get(
                        "response",
                        {},
                    )

                    raise RuntimeError(
                        failed.get(
                            "error",
                            {},
                        ).get(
                            "message",
                            "Genie Agent failed.",
                        )
                    )

            status.update(
                label=(
                    "Genie completed"
                    if latest_status == "completed"
                    else f"Genie status: {latest_status}"
                ),
                state=(
                    "complete"
                    if latest_status == "completed"
                    else "error"
                ),
            )

        if not final_response:
            raise RuntimeError(
                "Genie returned no completed response."
            )

        output = final_response.get(
            "output",
            [],
        )

        # Render only final assistant message content.
        assistant_messages = [
            item
            for item in output
            if item.get("type") == "message"
            and item.get("role") == "assistant"
        ]

        if assistant_messages:

            st.markdown(
                "### Genie answer"
            )

            for message in assistant_messages:

                for content in message.get(
                    "content",
                    [],
                ):

                    if content.get(
                        "type"
                    ) == "output_text":

                        st.markdown(
                            content.get(
                                "text",
                                "",
                            )
                        )

        if st.session_state.genie_conversation_id:
            st.caption(
                "Conversation ID: "
                f"`{st.session_state.genie_conversation_id}`"
            )

    except requests.HTTPError as exc:

        status_code = (
            exc.response.status_code
            if exc.response is not None
            else "unknown"
        )

        body = ""
        try:
            body = exc.response.text[:800]
        except Exception:
            pass

        if status_code == 409:
            st.warning(
                "This Genie conversation already has a response "
                "running. Wait for it to finish before asking a "
                "follow-up question."
            )
        elif status_code in (401, 403):
            st.error(
                "Genie authentication/permission failed. "
                "Verify the PAT identity has access to the Genie Agent "
                "and its underlying Unity Catalog data."
            )
        elif status_code == 404:
            st.error(
                "Genie Agent not found or the Agent Mode API is not "
                "available in this workspace."
            )
        else:
            st.error(
                f"Genie API failed HTTP {status_code}: {body}"
            )

    except Exception as exc:
        st.error(
            f"Genie request failed: {exc}"
        )

if st.session_state.genie_conversation_id:

    if st.button(
        "Start a new Genie conversation"
    ):
        st.session_state.genie_conversation_id = None
        st.rerun()

st.divider()

with st.container(border=True):

    section_title(
        "Governed source",
        "INVENT remains the semantic-model owner; Genie is a consumption channel.",
    )

    st.markdown(
        f"""
        **Domain:** `{entry.domain_name}`

        **Catalog:** `{entry.catalog}`

        **Schema:** `{entry.schema}`

        **Metric View:** `{entry.metric_view}`

        **Genie Agent:** `{space_id}`
        """
    )

    st.caption(
        "The Metric View is published in Unity Catalog and configured "
        "in the domain's Genie Agent. Genie queries current underlying "
        "data at runtime."
    )
